var app = (function(app) {
    app = app || {};
    app.text = app.text || {};
    app.text.he = {
        "general-yes": "כן",
        "general-no": "לא",
        "general-back": "חזור",
        "general-save": "שמור",
        "general-cancel": "בטל",
        "general-delete": "מחק",
        "general-add": "הוסף",
        "general-phone" : "טלפון:",
        "general-fax" : "פקס:",
        "general-address" : "כתובת:",
        "general-email" : "דוא\"ל:",
        "general-next" : 'הבא',
        "general-end" : 'סיום',
        "general-logout" : 'התנתק',
        "general-close" : 'סגור',
        "general-go-home" : 'חזרה לתפריט הראשי',
        "general-new" : "חדש",

        "active" : "פעילה",
        "new" : "נוצרה",
        "sent" : "נשלחה",

        "signin-forgot-pass" : "שכחתי סיסמא",

        "general-field-types-home": "בית",
        "general-field-types-work": "עבודה",
        "general-field-types-other": "אחר",

        "home-header": "קבלה בקליק",
        "home-cmd-receipt": "צור קבלה חדשה",
        "home-cmd-clients": "ניהול לקוחות",
        "home-cmd-items": "ניהול מוצרים ושירותים",
        "home-cmd-history": "צפה בקבלות קודמות",
        "home-cmd-settings": "הגדרות",

        "docs-new-header": "אשף קבלה חדשה",
        "docs-new-client-create": "לקוח חדש",
        "docs-new-client-edit": "ערוך לקוח",
        "docs-new-client-name": "שם הלקוח",
        "docs-new-client-search": "חפש",
        "docs-new-client-item-title": "פריט",
        "docs-new-client-item-name": "שם פריט",
        "docs-new-client-item-search": "חפש",
        "docs-new-client-item-list" : "רשימה",
        "docs-new-client-item-count": "כמות",
        "docs-new-client-item-price": "מחיר",
        "docs-new-item-subtotal": "סכום ביניים",
        "docs-new-item-remove": "הסר",
        "docs-new-item-add": "הוסף פריט",
        "docs-new-total-no-vat": 'סה"כ לפני מע"מ:',
        "docs-new-total-vat": 'מע"מ:',
        "docs-new-total-with-vat" : 'סה"כ:',
        "docs-new-receipt-num": "קבלה מספר: ",

        "docs-new-create": "הצג קבלה לפני שליחה",
        "docs-new-client-vat" : "הוספת מע\"מ",
        "docs-new-date" : 'תאריך: ',
        "docs-new-date-change" : 'שנה',

        "payment-type" : "אופן התשלום",
        "payment-type-cash" : "מזומן",
        "payment-type-bank" : "העברה בנקאית",
        "payment-type-check" : "המחאה",
        "payment-type-card" : "כרטיס אשראי",
        "payment-amount" : "הסכום ששולם",
        'payment-checkNum' : "מספר ההמחאה",
        'payment-checkBank' : "חשבון הבנק",
        'payment-checkDate' : "תאריך פרעון",
        'payment-cardType' : "סוג כרטיס",
        'payment-cardNum' : "מספר כרטיס",
        'payment-cardDate' : "תוקף",
        'payment-bankBranch' : "מספר סניף",
        'payment-bankAccount' : "מספר חשבון",
        "payments-remove" : "מחק תשלום",
        "payments-add" : "הוסף תשלום",
        "validation-client-title" : "חסרים פרטי לקוח",
        "validation-client-cmd" : 'פתח לקוח',
        "validation-client-no-name" : 'אין שם לקוח',
        "validation-client-no-contact" : 'אין פרטי התקשרות עם לקוח (דוא"ל או טלפון)',
        "validation-total-is-more-than-payed" : "לא שולמו",
        "validation-total-is-less-than-payed" : "מיותרים שולמו",
        "validation-total-review" : 'יש לתקן כך שהסכום ששולם ישתווה לסה"כ לתשלום',

        "docs-view-header" : "קבלות קודמות",
        "docs-view-from-date" : "מתאריך",
        "docs-view-no-docs" : "אין קבלות קודמות. לחץ ליצירת קבלה",

        "clients-view-no-clients" : "הרשימה ריקה. לחץ להוספת לקוחות",
        "clients-view-from-contacts":"יבא פרטים מספר הטלפונים",

        "clients-view-header": "ניהול לקוחות",
        "client-editor-header": "עריכת לקוח",
        "client-editor-name": "שם לקוח",
        "client-editor-email": "דואר אלקטרוני",
        "client-editor-phone": "טלפון",
        "client-editor-phones": "טלפונים",
        "client-editor-addresses": "כתובות",
        "client-editor-address": "כתובת",
        "client-editor-city": "עיר",
        "client-editor-zip": "מיקוד",
        "client-editor-delete": "מחק לקוח",

        "clients-remove-popup-header" : "מחיקת לקוח",
        "clients-remove-popup-content" : 'האם אתה בטוח שברצונך למחוק לקוח זה ממסד הנתונים?',
        "clients-remove-popup-delete" : 'מחק',
        "clients-remove-popup-cancel" : 'ביטול',

        "items-remove-popup-header" : "מחיקת פריט",
        "items-remove-popup-content" : 'האם אתה בטוח שברצונך למחוק פריט זה ממסד הנתונים?',
        "items-remove-popup-delete" : 'מחק',
        "items-remove-popup-cancel" : 'ביטול',

        "items-view-header" : "מוצרים ושירותים",
        "items-view-no-items" : "אין מוצרים או שירותים. לחץ להוספה",

        "item-editor-header" : "עריכת מוצר",
        "item-editor-item-name" : "שם המוצר או השירות",
        "item-editor-description" : "תאור המוצר או השירות",
        "item-editor-remove" : "מחק מוצר",

        "settings-account" : "הגדרות חשבון",
        "settings-business" : "הגדרות עסק",
        "settings-finance" : "הגדרות פיננסיות",

        "settings-account-email" : "דואר אלקטרוני",
        "settings-account-phone" : "טלפון",
        "settings-account-password" : "סיסמאת גישה לאתר",
        "settings-business-name" : "שם העסק",
        "settings-business-desc" : "תאור העסק",
        "settings-business-tel" : "טלפון",
        "settings-business-fax" : "פקס",
        "settings-business-email" : "דוא\"ל",
        "settings-business-address" : "כתובת",
        "settings-business-category" : "תחום עיסוק",
        "settings-cmd-change-photo" : "העלה לוגו חדש",

        "settings-business-demo" : "דוגמא לכותרת הקבלה",

        "settings-finance-add-vat" : "האם להוסיף מע\"ם",
        "settings-finance-vat-val" : "שיעור המע\"ם באחוזים",
        "settings-finance-doc-counter" : "מספר הקבלה הבאה",

        "welcome-signup" : 'הרשמה',
        "welcome-signin" : 'כניסה',

        "docs-send-header" : 'שליחת קבלה ללקוח',
        "docs-send-desc" : 'בחר את אמצעי הקשר בו תרצה לעביר את הקבלה ללקוח',
        "docs-send-after" : 'הקבלה נשלחה ללקוח בהצלחה',
        "docs-sent-select-bonus" : 'בחר הטבה ללקוח',
        "docs-send-for-title" : 'לכבוד: ',

        "settings-business-category-options" : ['בחר תחום עיסוק', 'אבטחה וחקירות', 'אבטחת איכות', 'אדמיניסטרציה', 'אופנה ותעשיית טקסטיל', 'אחזקה ותחזוקה', 'אינטרנט', 'ביטוח', 'בניין ותשתיות', 'גרפיקה ועיצוב', 'חו"ל לצעירים', 'חומרה, חשמל ואלקטרוניקה', 'חינוך והדרכה', 'חקלאות וטבע', 'טיפול, ייעוץ ורווחה', 'יופי וטיפוח', 'ייצור ותעשייה', 'כללי', 'כספים וכלכלה', 'לוגיסטיקה ותפעול', 'מדעים ומו"פ כללי', 'מזון ומסעדנות', 'מכירות', 'מלונאות ותיירות', 'משאבי אנוש ואסטרטגיה', 'משפטים ועריכת דין', 'נדל"ן', 'ניהול בכיר', 'ספורט', 'עריכה והפקת תוכן', 'פרסום ותקשורת', 'רכב, תחבורה והובלות', 'רפואה ובריאות', 'שיווק', 'תוכנה ותשתיות IT', 'תמיכה ושירות לקוחות', 'תעופה וימאות', 'תקשורת ומדיה']
    };

    return app;
}(app));
